# Generated by Django 5.2.14 on 2026-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_config_and_grade_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentconfig',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('letter', 'Letter grades (A-F)'), ('numerical', 'Numerical grades (1-9)')], help_text='Required when result type includes grades.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradeband',
            name='grade',
            field=models.CharField(help_text='Letter (A-F) or numerical (1-9) grade label.', max_length=10),
        ),
    ]
