export type {
  SubjectScope,
  StreamForSetup,
  SubjectGroupForSetup,
  SubjectForSetup,
  ClassSubjectForSetup,
  ClassForSetup,
  LevelForSetup,
  LevelWithRelatedClassesAndSubjects,
  AddSubjectPayload,
  AddSubjectResponse,
  AddSubjectGroupResponse,
  AddClassPayload,
  AddStreamPayload,
  CurriculumHandlers,
} from '@/components/curriculum'
