# Generated by Django 5.2.14 on 2026-06-22 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_address_school_box_address_school_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SchoolSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('school_profile', 'School profile'), ('academic_year_term', 'Academic year and term'), ('classes_and_subjects', 'Classes and subjects'), ('assessment', 'Assessment'), ('fees', 'Fees'), ('teachers', 'Teachers'), ('staff', 'Staff'), ('completed', 'Completed')], default='school_profile', max_length=50)),
                ('completed_steps', models.JSONField(default=list)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup', to='schools.school')),
            ],
        ),
    ]
