# Generated by Django 5.2.14 on 2026-06-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_setup_completed_school_setup_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsetup',
            name='current_step',
            field=models.CharField(choices=[('school_profile', 'School profile'), ('academic_year_term', 'Academic year & term'), ('classes_and_subjects', 'Classes & subjects'), ('assessment', 'Assessment'), ('fees', 'Fees'), ('teachers', 'Teachers'), ('staff', 'Staff'), ('completed', 'Completed')], default='school_profile', max_length=50),
        ),
    ]
