# Generated by Django 5.2.14 on 2026-06-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_schoolsetup_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school-management-system/school-logos/'),
        ),
        migrations.AlterField(
            model_name='schoolsetup',
            name='current_step',
            field=models.CharField(choices=[('school_profile', 'School profile'), ('academic_year_term', 'Academic year & term'), ('classes_and_subjects', 'Classes & subjects'), ('assessment', 'Assessment'), ('fees', 'Fees'), ('teachers', 'Add Teachers'), ('staff', 'Add Staff'), ('completed', 'Completed')], default='school_profile', max_length=50),
        ),
    ]
