# Generated by Django 5.2.14 on 2026-06-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_term_school_active_term_per_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['start_date']},
        ),
    ]
