ghana_education_curriculum = {
    "Pre-School": {
        "order": 1,
        "subject_scope": "class",
        "allows_custom_classes": True,
        "classes": [
            "Crèche / Daycare",
            "Nursery 1",
            "Nursery 2",
        ],
        "description": "Ages 0 - 5",
        "subjects": {
            "Crèche / Daycare": [
                "Sensory Stimulation (colors, sounds, textures)",
                "Motor Skills Development (crawling, grasping)",
                "Social & Communication Play (singing, rhyming)",
                "Basic Habit Training (routines, feeding)",
            ],
            "Nursery 1": [
                "Pre-Literacy & Communication (phonics, letter recognition)",
                "Pre-Numeracy (counting, shapes, colors)",
                "Creative Activities (coloring, molding, fine motor skills)",
                "Environmental & Social Exploration (body parts, manners, self-awareness)",
            ],
            "Nursery 2": [
                "Pre-Literacy & Communication (phonics, letter recognition)",
                "Pre-Numeracy (counting, shapes, colors)",
                "Creative Activities (coloring, molding, fine motor skills)",
                "Environmental & Social Exploration (body parts, manners, self-awareness)",
            ],
        },
    },
    "Kindergarten": {
        "order": 2,
        "subject_scope": "level",
        "classes": ["KG 1", "KG 2"],
        "description": "Kindergarten 1 & 2",
        "subjects": [
            "Language and Literacy",
            "Numeracy",
            "Our World and Our People",
            "Creative Arts",
            "Physical Education",
            "Religious and Moral Education",
        ],
    },
    "Lower Primary": {
        "order": 3,
        "subject_scope": "level",
        "classes": ["Basic 1", "Basic 2", "Basic 3"],
        "description": "Basic 1, 2 & 3",
        "subjects": [
            "English Language",
            "Mathematics",
            "Science",
            "Ghanaian Language and Culture",
            "Our World and Our People",
            "Religious and Moral Education",
            "Creative Arts",
            "Physical Education",
        ],
    },
    "Upper Primary": {
        "order": 4,
        "subject_scope": "level",
        "classes": ["Basic 4", "Basic 5", "Basic 6"],
        "description": "Basic 4, 5 & 6",
        "subjects": [
            "English Language",
            "Mathematics",
            "Science",
            "Ghanaian Language and Culture",
            "Our World and Our People",
            "Religious and Moral Education",
            "Creative Arts",
            "Physical Education",
            "Computing",
            "History",
            "French",
        ],
    },
    "Junior High School": {
        "order": 5,
        "subject_scope": "level",
        "classes": ["JHS 1", "JHS 2", "JHS 3"],
        "description": "JHS 1, 2 & 3",
        "subjects": [
            "English Language",
            "Mathematics",
            "Integrated Science",
            "Social Studies",
            "Computing",
            "Career Technology",
            "Creative Arts and Design",
            "Ghanaian Language",
            "Religious and Moral Education",
            "French",
        ],
    },
}
