# Generated by Django 5.2.14 on 2026-07-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_enrollment_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
