# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0007_classenrollment_stream'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(
                fields=('school', 'student_id'),
                name='unique_student_id_per_school',
            ),
        ),
    ]
