# Generated by Django 5.2.14 on 2026-07-07 06:58

import academics.curriculum_guard
import academics.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order within the level.')),
            ],
            options={
                'ordering': ['level__order', 'order', 'name'],
            },
            bases=(academics.mixins.SystemGeneratedRecordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClassStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Leave blank for the default stream, e.g. A, B, Lily.', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
            ],
            bases=(academics.mixins.SystemGeneratedRecordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField()),
                ('version', models.CharField(default='2024', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='When true, this version is used for new school provisioning.')),
            ],
            options={
                'ordering': ['code', '-version'],
            },
            bases=(academics.curriculum_guard.ImmutableCurriculumMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CurriculumClassLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(academics.curriculum_guard.ImmutableCurriculumMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CurriculumLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject_scope', models.CharField(choices=[('level', 'Shared across classes'), ('class', 'Configured per class')], default='level', max_length=10)),
                ('allows_custom_classes', models.BooleanField(default=False, help_text='When true, schools may add their own classes under this level.')),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(academics.curriculum_guard.ImmutableCurriculumMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(academics.curriculum_guard.ImmutableCurriculumMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('subject_scope', models.CharField(choices=[('level', 'Shared across classes'), ('class', 'Configured per class')], default='level', max_length=10)),
                ('allows_custom_classes', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order within the school.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(academics.mixins.SystemGeneratedRecordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudentSubjectGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(academics.mixins.SystemGeneratedRecordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
