# Generated by Django 5.2.14 on 2026-07-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classstream',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_curriculum_code_version'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='curriculum_class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_class_levels', to='academics.curriculumclasslevel'),
        ),
        migrations.AddField(
            model_name='curriculumlevel',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='curriculumclasslevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='academics.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='curriculum_class_level',
            field=models.ForeignKey(blank=True, help_text='When set, this subject applies only to the linked template class.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.curriculumclasslevel'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='curriculum_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_class_subjects', to='academics.curriculumsubject'),
        ),
        migrations.AddField(
            model_name='level',
            name='curriculum_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_levels', to='academics.curriculumlevel'),
        ),
        migrations.AddField(
            model_name='level',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='academics.level'),
        ),
        migrations.AddField(
            model_name='studentsubjectgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_groups', to='schools.academicyear'),
        ),
        migrations.AddField(
            model_name='studentsubjectgroup',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_assignments', to='academics.classsubject'),
        ),
        migrations.AddField(
            model_name='studentsubjectgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_group_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.classsubject'),
        ),
        migrations.AddField(
            model_name='studentsubjectgroup',
            name='subject_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='academics.subjectgroup'),
        ),
        migrations.AddConstraint(
            model_name='classstream',
            constraint=models.UniqueConstraint(fields=('class_level', 'name'), name='unique_stream_name_per_class_level'),
        ),
        migrations.AddConstraint(
            model_name='classstream',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('class_level',), name='unique_default_stream_per_class_level'),
        ),
        migrations.AddConstraint(
            model_name='curriculumlevel',
            constraint=models.UniqueConstraint(fields=('curriculum', 'name'), name='unique_curriculum_level_name'),
        ),
        migrations.AddConstraint(
            model_name='curriculumclasslevel',
            constraint=models.UniqueConstraint(fields=('level', 'name'), name='unique_curriculum_class_level_name'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('curriculum_class_level__isnull', True)), fields=('level', 'name'), name='unique_level_scoped_curriculum_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('curriculum_class_level__isnull', False)), fields=('curriculum_class_level', 'name'), name='unique_class_scoped_curriculum_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_level_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(fields=('school', 'level', 'name'), name='unique_class_level_name_per_level'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_level', 'subject'), name='unique_subject_per_class_level'),
        ),
        migrations.AddConstraint(
            model_name='subjectgroup',
            constraint=models.UniqueConstraint(fields=('class_subject', 'name'), name='unique_subject_group_per_class_subject'),
        ),
        migrations.AddConstraint(
            model_name='studentsubjectgroup',
            constraint=models.UniqueConstraint(fields=('student', 'class_subject', 'academic_year'), name='unique_student_class_subject_per_academic_year'),
        ),
    ]
