# Generated by Django 5.2.14 on 2026-07-14 05:05

import academics.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_seed_ghana_curriculum'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('curriculum_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_level_subjects', to='academics.curriculumsubject')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='academics.level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_subjects', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name'],
                'constraints': [models.UniqueConstraint(fields=('level', 'subject'), name='unique_subject_per_level')],
            },
            bases=(academics.mixins.SystemGeneratedRecordMixin, models.Model),
        ),
    ]
