# Generated by Django 5.2.14 on 2026-07-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_fee_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['name']},
        ),
    ]
