# Generated by Django 5.2.14 on 2026-08-25 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_payment_options_alter_receipt_options_and_more'),
        ('schools', '0001_initial'),
        ('students', '0009_student_address_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('advance_credit', 'Advance Credit'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFeeCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original advance amount created from an excess payment.', max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='How much of this advance is still unused.', max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('applied', 'Applied'), ('refunded', 'Refunded')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_credits', to='schools.school')),
                ('source_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_credits', to='fees.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_credits', to='students.student')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_credit_amount_positive'), models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='fee_credit_remaining_non_negative')],
            },
        ),
    ]
